-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.attribute_definitions
(
    id serial NOT NULL,
    name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    "values" json NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attribute_definitions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_attribute_definitions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.brands
(
    id serial NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(140) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT brands_pkey PRIMARY KEY (id),
    CONSTRAINT brands_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    id serial NOT NULL,
    cart_id integer NOT NULL,
    product_id integer NOT NULL,
    variant_id integer,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(12, 2) NOT NULL,
    product_name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    sku character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.carts
(
    id serial NOT NULL,
    session_key character varying(120) COLLATE pg_catalog."default",
    user_id integer,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_id integer,
    coupon_code character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT carts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id serial NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(140) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    parent_id integer,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_url character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.compare_items
(
    id serial NOT NULL,
    compare_list_id integer NOT NULL,
    product_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT compare_items_pkey PRIMARY KEY (id),
    CONSTRAINT uq_compare_product UNIQUE (compare_list_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.compare_lists
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT compare_lists_pkey PRIMARY KEY (id),
    CONSTRAINT compare_lists_customer_id_key UNIQUE (customer_id)
);

CREATE TABLE IF NOT EXISTS public.coupon_usages
(
    id serial NOT NULL,
    coupon_id integer NOT NULL,
    customer_id integer NOT NULL,
    order_id integer,
    used_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    discount_amount numeric(12, 2),
    CONSTRAINT coupon_usages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coupons
(
    id serial NOT NULL,
    code character varying(40) COLLATE pg_catalog."default" NOT NULL,
    name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    discount_type character varying(16) COLLATE pg_catalog."default" NOT NULL,
    discount_value numeric(12, 2) NOT NULL,
    min_order_amount numeric(12, 2),
    max_uses integer,
    used_count integer NOT NULL DEFAULT 0,
    starts_at timestamp without time zone,
    ends_at timestamp without time zone,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT coupons_pkey PRIMARY KEY (id),
    CONSTRAINT uq_coupons_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.courier_accounts
(
    id serial NOT NULL,
    provider character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'manual'::character varying,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    config_json text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT courier_accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_addresses
(
    id serial NOT NULL,
    user_id integer,
    full_name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(40) COLLATE pg_catalog."default" NOT NULL,
    line1 character varying(255) COLLATE pg_catalog."default" NOT NULL,
    line2 character varying(255) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    state character varying(100) COLLATE pg_catalog."default" NOT NULL,
    postal_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    country character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT 'India'::character varying,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_id integer,
    CONSTRAINT customer_addresses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(40) COLLATE pg_catalog."default",
    hashed_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    email_verified boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.feedbacks
(
    id serial NOT NULL,
    customer_id integer,
    name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(200) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    status character varying(32) COLLATE pg_catalog."default" NOT NULL DEFAULT 'new'::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT feedbacks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory_items
(
    id serial NOT NULL,
    product_id integer,
    variant_id integer,
    sku character varying(64) COLLATE pg_catalog."default",
    quantity integer NOT NULL DEFAULT 0,
    reserved integer NOT NULL DEFAULT 0,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory_settings
(
    id serial NOT NULL,
    low_stock_threshold integer NOT NULL DEFAULT 10,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_settings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    channel character varying(16) COLLATE pg_catalog."default" NOT NULL DEFAULT 'email'::character varying,
    template_key character varying(80) COLLATE pg_catalog."default" NOT NULL,
    recipient character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(255) COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default",
    status character varying(16) COLLATE pg_catalog."default" NOT NULL DEFAULT 'queued'::character varying,
    related_order_id integer,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    product_id integer,
    variant_id integer,
    sku character varying(64) COLLATE pg_catalog."default",
    name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(12, 2) NOT NULL,
    line_total numeric(12, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_status_history
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    from_status character varying(20) COLLATE pg_catalog."default",
    to_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    note character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_status_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    order_number character varying(40) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    payment_method character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'cod'::character varying,
    subtotal numeric(12, 2) NOT NULL DEFAULT '0'::numeric,
    shipping_amount numeric(12, 2) NOT NULL DEFAULT '0'::numeric,
    tax_amount numeric(12, 2) NOT NULL DEFAULT '0'::numeric,
    discount_amount numeric(12, 2) NOT NULL DEFAULT '0'::numeric,
    total numeric(12, 2) NOT NULL DEFAULT '0'::numeric,
    currency character varying(8) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    shipping_name character varying(160) COLLATE pg_catalog."default",
    shipping_phone character varying(40) COLLATE pg_catalog."default",
    shipping_line1 character varying(255) COLLATE pg_catalog."default",
    shipping_line2 character varying(255) COLLATE pg_catalog."default",
    shipping_city character varying(100) COLLATE pg_catalog."default",
    shipping_state character varying(100) COLLATE pg_catalog."default",
    shipping_postal_code character varying(20) COLLATE pg_catalog."default",
    shipping_country character varying(100) COLLATE pg_catalog."default",
    coupon_code character varying(40) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_id integer,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT uq_orders_order_number UNIQUE (order_number)
);

CREATE TABLE IF NOT EXISTS public.payment_events
(
    id serial NOT NULL,
    payment_id integer,
    event_id character varying(120) COLLATE pg_catalog."default" NOT NULL,
    event_type character varying(60) COLLATE pg_catalog."default" NOT NULL,
    signature_valid boolean NOT NULL DEFAULT false,
    payload text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_events_pkey PRIMARY KEY (id),
    CONSTRAINT uq_payment_events_event_id UNIQUE (event_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    provider character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'razorpay'::character varying,
    provider_order_id character varying(80) COLLATE pg_catalog."default",
    provider_payment_id character varying(80) COLLATE pg_catalog."default",
    amount numeric(12, 2) NOT NULL,
    currency character varying(8) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'created'::character varying,
    method character varying(30) COLLATE pg_catalog."default",
    raw_payload text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_attributes
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    "values" json NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_attributes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_media
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    alt_text character varying(200) COLLATE pg_catalog."default",
    sort_order integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_media_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_variants
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    sku character varying(64) COLLATE pg_catalog."default" NOT NULL,
    price numeric(12, 2),
    stock integer NOT NULL DEFAULT 0,
    options json NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_variants_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_variants_sku UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(180) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(12, 2) NOT NULL,
    compare_at_price numeric(12, 2),
    sku character varying(64) COLLATE pg_catalog."default",
    category_id integer,
    is_published boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    short_description text COLLATE pg_catalog."default",
    discount_percent numeric(5, 2),
    manufacturer_name character varying(160) COLLATE pg_catalog."default",
    manufacturer_brand character varying(160) COLLATE pg_catalog."default",
    stock integer NOT NULL DEFAULT 0,
    tags character varying(500) COLLATE pg_catalog."default",
    visibility character varying(32) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
    published_at timestamp without time zone,
    exchangeable boolean NOT NULL DEFAULT false,
    refundable boolean NOT NULL DEFAULT false,
    brand_id integer,
    is_featured boolean NOT NULL DEFAULT false,
    is_trending boolean NOT NULL DEFAULT false,
    is_best_seller boolean NOT NULL DEFAULT false,
    seo_title character varying(200) COLLATE pg_catalog."default",
    seo_description character varying(500) COLLATE pg_catalog."default",
    deleted_at timestamp without time zone,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT uq_products_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    token_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.refunds
(
    id serial NOT NULL,
    payment_id integer NOT NULL,
    order_id integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    reason character varying(255) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'initiated'::character varying,
    provider_refund_id character varying(80) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refunds_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.review_images
(
    id serial NOT NULL,
    review_id integer NOT NULL,
    url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT review_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    customer_id integer NOT NULL,
    rating integer NOT NULL,
    title character varying(200) COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default",
    is_verified_purchase boolean NOT NULL DEFAULT false,
    is_approved boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.shipment_events
(
    id serial NOT NULL,
    shipment_id integer NOT NULL,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    message character varying(255) COLLATE pg_catalog."default",
    event_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'manual'::character varying,
    CONSTRAINT shipment_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.shipments
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    courier_provider character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'manual'::character varying,
    awb character varying(80) COLLATE pg_catalog."default",
    label_url character varying(500) COLLATE pg_catalog."default",
    status character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'created'::character varying,
    pickup_scheduled_at timestamp without time zone,
    exception_flag boolean NOT NULL DEFAULT false,
    exception_reason character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT shipments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stock_movements
(
    id serial NOT NULL,
    inventory_item_id integer NOT NULL,
    delta integer NOT NULL,
    reason character varying(160) COLLATE pg_catalog."default" NOT NULL,
    reference character varying(160) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_movements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.store_settings
(
    id serial NOT NULL,
    store_name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    legal_name character varying(200) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(40) COLLATE pg_catalog."default",
    address_line1 character varying(255) COLLATE pg_catalog."default",
    address_line2 character varying(255) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    state character varying(100) COLLATE pg_catalog."default",
    postal_code character varying(20) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    currency character varying(8) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    timezone character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Asia/Kolkata'::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT store_settings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tax_rules
(
    id serial NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    code character varying(40) COLLATE pg_catalog."default" NOT NULL,
    rate_percent numeric(5, 2) NOT NULL,
    is_inclusive boolean NOT NULL DEFAULT false,
    country character varying(100) COLLATE pg_catalog."default",
    state character varying(100) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tax_rules_pkey PRIMARY KEY (id),
    CONSTRAINT uq_tax_rules_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.wishlist_items
(
    id serial NOT NULL,
    wishlist_id integer NOT NULL,
    product_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wishlist_items_pkey PRIMARY KEY (id),
    CONSTRAINT uq_wishlist_product UNIQUE (wishlist_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.wishlists
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wishlists_pkey PRIMARY KEY (id),
    CONSTRAINT wishlists_customer_id_key UNIQUE (customer_id)
);

ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id)
    REFERENCES public.carts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_cart_items_cart_id
    ON public.cart_items(cart_id);


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_cart_items_product_id
    ON public.cart_items(product_id);


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT fk_cart_items_variant FOREIGN KEY (variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_cart_items_variant_id
    ON public.cart_items(variant_id);


ALTER TABLE IF EXISTS public.carts
    ADD CONSTRAINT fk_carts_customer_id FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_carts_customer_id
    ON public.carts(customer_id);


ALTER TABLE IF EXISTS public.carts
    ADD CONSTRAINT fk_carts_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_carts_user_id
    ON public.carts(user_id);


ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_categories_parent_id
    ON public.categories(parent_id);


ALTER TABLE IF EXISTS public.compare_items
    ADD CONSTRAINT compare_items_compare_list_id_fkey FOREIGN KEY (compare_list_id)
    REFERENCES public.compare_lists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_compare_items_compare_list_id
    ON public.compare_items(compare_list_id);


ALTER TABLE IF EXISTS public.compare_items
    ADD CONSTRAINT compare_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_compare_items_product_id
    ON public.compare_items(product_id);


ALTER TABLE IF EXISTS public.compare_lists
    ADD CONSTRAINT compare_lists_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS compare_lists_customer_id_key
    ON public.compare_lists(customer_id);


ALTER TABLE IF EXISTS public.coupon_usages
    ADD CONSTRAINT coupon_usages_coupon_id_fkey FOREIGN KEY (coupon_id)
    REFERENCES public.coupons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_coupon_usages_coupon_id
    ON public.coupon_usages(coupon_id);


ALTER TABLE IF EXISTS public.coupon_usages
    ADD CONSTRAINT coupon_usages_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_coupon_usages_customer_id
    ON public.coupon_usages(customer_id);


ALTER TABLE IF EXISTS public.coupon_usages
    ADD CONSTRAINT coupon_usages_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_coupon_usages_order_id
    ON public.coupon_usages(order_id);


ALTER TABLE IF EXISTS public.customer_addresses
    ADD CONSTRAINT fk_customer_addresses_customer_id FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_customer_addresses_customer_id
    ON public.customer_addresses(customer_id);


ALTER TABLE IF EXISTS public.customer_addresses
    ADD CONSTRAINT fk_customer_addresses_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_customer_addresses_user_id
    ON public.customer_addresses(user_id);


ALTER TABLE IF EXISTS public.feedbacks
    ADD CONSTRAINT feedbacks_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_feedbacks_customer_id
    ON public.feedbacks(customer_id);


ALTER TABLE IF EXISTS public.inventory_items
    ADD CONSTRAINT fk_inventory_items_product FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_inventory_items_product_id
    ON public.inventory_items(product_id);


ALTER TABLE IF EXISTS public.inventory_items
    ADD CONSTRAINT fk_inventory_items_variant FOREIGN KEY (variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_inventory_items_variant_id
    ON public.inventory_items(variant_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk_notifications_order FOREIGN KEY (related_order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_notifications_related_order_id
    ON public.notifications(related_order_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_order_items_order_id
    ON public.order_items(order_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT fk_order_items_product FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_order_items_product_id
    ON public.order_items(product_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT fk_order_items_variant FOREIGN KEY (variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_order_items_variant_id
    ON public.order_items(variant_id);


ALTER TABLE IF EXISTS public.order_status_history
    ADD CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_order_status_history_order_id
    ON public.order_status_history(order_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_orders_customer_id
    ON public.orders(customer_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_orders_user_id
    ON public.orders(user_id);


ALTER TABLE IF EXISTS public.payment_events
    ADD CONSTRAINT fk_payment_events_payment FOREIGN KEY (payment_id)
    REFERENCES public.payments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_payment_events_payment_id
    ON public.payment_events(payment_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_payments_order FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_payments_order_id
    ON public.payments(order_id);


ALTER TABLE IF EXISTS public.product_attributes
    ADD CONSTRAINT fk_product_attributes_product FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_product_attributes_product_id
    ON public.product_attributes(product_id);


ALTER TABLE IF EXISTS public.product_media
    ADD CONSTRAINT fk_product_media_product FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_product_media_product_id
    ON public.product_media(product_id);


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT fk_product_variants_product FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_product_variants_product_id
    ON public.product_variants(product_id);


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk_products_brand_id FOREIGN KEY (brand_id)
    REFERENCES public.brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_products_brand_id
    ON public.products(brand_id);


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_products_category_id
    ON public.products(category_id);


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_customer_id
    ON public.refresh_tokens(customer_id);


ALTER TABLE IF EXISTS public.refunds
    ADD CONSTRAINT fk_refunds_order FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_refunds_order_id
    ON public.refunds(order_id);


ALTER TABLE IF EXISTS public.refunds
    ADD CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id)
    REFERENCES public.payments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_refunds_payment_id
    ON public.refunds(payment_id);


ALTER TABLE IF EXISTS public.review_images
    ADD CONSTRAINT review_images_review_id_fkey FOREIGN KEY (review_id)
    REFERENCES public.reviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_review_images_review_id
    ON public.review_images(review_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reviews_customer_id
    ON public.reviews(customer_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reviews_product_id
    ON public.reviews(product_id);


ALTER TABLE IF EXISTS public.shipment_events
    ADD CONSTRAINT fk_shipment_events_shipment FOREIGN KEY (shipment_id)
    REFERENCES public.shipments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_shipment_events_shipment_id
    ON public.shipment_events(shipment_id);


ALTER TABLE IF EXISTS public.shipments
    ADD CONSTRAINT fk_shipments_order FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_shipments_order_id
    ON public.shipments(order_id);


ALTER TABLE IF EXISTS public.stock_movements
    ADD CONSTRAINT fk_stock_movements_inventory_item FOREIGN KEY (inventory_item_id)
    REFERENCES public.inventory_items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_stock_movements_inventory_item_id
    ON public.stock_movements(inventory_item_id);


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.wishlist_items
    ADD CONSTRAINT wishlist_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_wishlist_items_product_id
    ON public.wishlist_items(product_id);


ALTER TABLE IF EXISTS public.wishlist_items
    ADD CONSTRAINT wishlist_items_wishlist_id_fkey FOREIGN KEY (wishlist_id)
    REFERENCES public.wishlists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_wishlist_items_wishlist_id
    ON public.wishlist_items(wishlist_id);


ALTER TABLE IF EXISTS public.wishlists
    ADD CONSTRAINT wishlists_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_wishlists_customer_id
    ON public.wishlists(customer_id);

END;