-- =============================================================================
-- Reset ecommerce seed data (keeps admin users/roles)
-- Classic Way T-Shirt seed · shared admin + shopping PostgreSQL
-- Generated by database/seeds/generate_tshirt_sql.py
-- UUIDs are deterministic (uuid5) for easy S3 URL updates later.
-- =============================================================================

BEGIN;

TRUNCATE TABLE
  coupon_usages,
  review_images,
  reviews,
  notifications,
  shipment_events,
  shipments,
  refunds,
  payment_events,
  payments,
  order_status_history,
  order_items,
  orders,
  cart_items,
  carts,
  wishlist_items,
  wishlists,
  compare_items,
  compare_lists,
  customer_addresses,
  refresh_tokens,
  customers,
  stock_movements,
  inventory_items,
  product_media,
  product_variants,
  product_attributes,
  products,
  attribute_definitions,
  brands,
  categories,
  coupons
RESTART IDENTITY CASCADE;

COMMIT;
