-- =============================================================================
-- 01 Master catalog — attributes, brands, categories, settings
-- Classic Way T-Shirt seed · shared admin + shopping PostgreSQL
-- Generated by database/seeds/generate_tshirt_sql.py
-- UUIDs are deterministic (uuid5) for easy S3 URL updates later.
-- =============================================================================

BEGIN;

-- Attribute definitions (filter facets)
INSERT INTO attribute_definitions (id, name, values, sort_order, is_active) VALUES
  ('dba4ed6f-4c2f-5084-9992-48a582b22a7b'::uuid, 'Color', '["Black", "White", "Navy", "Olive", "Red", "Maroon", "Grey", "Charcoal", "Beige", "Cream", "Yellow", "Mustard", "Green", "Forest", "Blue", "Sky Blue", "Purple", "Pink", "Orange", "Brown"]'::json, 1, true),
  ('f00eae14-45ca-5abf-aa77-3991f2d99609'::uuid, 'Size', '["XS", "S", "M", "L", "XL", "XXL", "XXXL"]'::json, 2, true),
  ('dd194efd-3e42-54f3-b916-89fc0c34dc72'::uuid, 'Fabric', '["Cotton", "Bio Wash", "Organic Cotton", "Poly Cotton", "Dry Fit", "Linen Blend"]'::json, 3, true),
  ('b7d93afd-b687-5f82-989a-a7764dea7a2d'::uuid, 'Neck Type', '["Round Neck", "Polo", "V Neck", "Henley", "Mandarin"]'::json, 4, true),
  ('aeb2779d-d900-5b11-b725-7ecbbd1d7380'::uuid, 'Sleeve Type', '["Half Sleeve", "Full Sleeve", "Sleeveless"]'::json, 5, true),
  ('5427d0ec-68db-576f-a1bc-7ed736445b33'::uuid, 'Gender', '["Men", "Women", "Unisex", "Kids"]'::json, 6, true)
ON CONFLICT (name) DO NOTHING;

-- Brands (20)
INSERT INTO brands (id, name, slug, is_active) VALUES
  ('050184c6-7eaf-594b-8c79-99380672cbd6'::uuid, 'Classic Way', 'classic-way', true),
  ('78592677-89c5-5c40-b748-b693f8aadeed'::uuid, 'Urban Wear', 'urban-wear', true),
  ('a47e7111-72bf-5cc7-9455-f3b123276bdf'::uuid, 'Street Style', 'street-style', true),
  ('8aec3bfd-7614-5a7e-8b6d-4aa2eeb5c4b7'::uuid, 'Elite Cotton', 'elite-cotton', true),
  ('a680eb75-f11f-5cec-b316-b01f2d0c2697'::uuid, 'Trend Fit', 'trend-fit', true),
  ('58a3e448-8f3b-5d49-a0e1-6b005b34eab1'::uuid, 'Cotton Co', 'cotton-co', true),
  ('0470a177-4ea6-5c46-b94f-47d5ca9bff7b'::uuid, 'Valaiyagam', 'valaiyagam', true),
  ('2d8f73b8-7484-5aff-91e7-f8fc20f5b517'::uuid, 'Urban Thread', 'urban-thread', true),
  ('ef296b0f-ca85-5902-8f64-3d16c9952593'::uuid, 'North Loom', 'north-loom', true),
  ('b85bfc9c-d90f-5667-ba4b-6c89ca2373f2'::uuid, 'Coast & Co', 'coast-and-co', true),
  ('18fbcdc7-9623-5dae-954f-de65f78690ba'::uuid, 'Peak Athletic', 'peak-athletic', true),
  ('f3eb3176-71d5-534e-a9d2-86aff8f248e6'::uuid, 'Soft Form', 'soft-form', true),
  ('d88da92b-fd7d-55b0-b62a-e44de7478ae4'::uuid, 'Bold Ink', 'bold-ink', true),
  ('a5ec6502-2b30-54ae-824c-1ccccdd12562'::uuid, 'Daily Knit', 'daily-knit', true),
  ('5ae199f7-eff3-57c0-8d56-798f696d1719'::uuid, 'Harbor Tees', 'harbor-tees', true),
  ('58b12053-a297-52aa-9b1a-a78a512906e0'::uuid, 'Metro Basics', 'metro-basics', true),
  ('beb43dde-6f75-5029-b252-39753110452a'::uuid, 'Indie Loom', 'indie-loom', true),
  ('ef307676-746a-5912-956b-d12f4052754e'::uuid, 'Aether Wear', 'aether-wear', true),
  ('f598dbc6-9ec0-582c-b529-3cc40879c8f5'::uuid, 'Cedar Street', 'cedar-street', true),
  ('69d12594-37c8-5e7a-bc6e-ef15d89d6c9d'::uuid, 'Nova Cotton', 'nova-cotton', true)
ON CONFLICT (slug) DO NOTHING;

-- Categories (12) with parent tree
INSERT INTO categories (id, name, slug, description, parent_id, is_active, sort_order, image_url) VALUES
  ('36f626d2-dfde-5e0f-a4b9-8e18af3f4f37'::uuid, 'Men''s T-Shirts', 'mens-t-shirts', 'Men''s T-Shirts collection for Classic Way storefront', NULL, true, 1, 'https://placehold.co/900x1100/2d3748/ffffff?text=Men''s+T-Shirts'),
  ('3f796f09-ddf9-5f55-9f8a-1bafefeda2e8'::uuid, 'Women''s T-Shirts', 'womens-t-shirts', 'Women''s T-Shirts collection for Classic Way storefront', NULL, true, 2, 'https://placehold.co/900x1100/2d3748/ffffff?text=Women''s+T-Shirts'),
  ('06466540-898b-5766-8e73-f8880c92e0c5'::uuid, 'Oversized', 'oversized', 'Oversized collection for Classic Way storefront', '36f626d2-dfde-5e0f-a4b9-8e18af3f4f37'::uuid, true, 3, 'https://placehold.co/900x1100/2d3748/ffffff?text=Oversized'),
  ('0641a4dd-fa66-570e-82a4-24245249db70'::uuid, 'Polo', 'polo', 'Polo collection for Classic Way storefront', '36f626d2-dfde-5e0f-a4b9-8e18af3f4f37'::uuid, true, 4, 'https://placehold.co/900x1100/2d3748/ffffff?text=Polo'),
  ('617a811f-e536-5d6f-8a07-81bfa33598f7'::uuid, 'Printed', 'printed', 'Printed collection for Classic Way storefront', '36f626d2-dfde-5e0f-a4b9-8e18af3f4f37'::uuid, true, 5, 'https://placehold.co/900x1100/2d3748/ffffff?text=Printed'),
  ('2dc41351-caf9-54b9-aa3d-fa985d17bf24'::uuid, 'Graphic', 'graphic', 'Graphic collection for Classic Way storefront', '3f796f09-ddf9-5f55-9f8a-1bafefeda2e8'::uuid, true, 6, 'https://placehold.co/900x1100/2d3748/ffffff?text=Graphic'),
  ('7d22ae05-93fe-58aa-88d3-1d2b2c8fab5c'::uuid, 'Full Sleeve', 'full-sleeve', 'Full Sleeve collection for Classic Way storefront', '36f626d2-dfde-5e0f-a4b9-8e18af3f4f37'::uuid, true, 7, 'https://placehold.co/900x1100/2d3748/ffffff?text=Full+Sleeve'),
  ('d27ecd87-9b5d-5189-88ea-2dd4b2429434'::uuid, 'Half Sleeve', 'half-sleeve', 'Half Sleeve collection for Classic Way storefront', '36f626d2-dfde-5e0f-a4b9-8e18af3f4f37'::uuid, true, 8, 'https://placehold.co/900x1100/2d3748/ffffff?text=Half+Sleeve'),
  ('87409f35-a551-51b0-8beb-49ea75ed34d9'::uuid, 'Premium Cotton', 'premium-cotton', 'Premium Cotton collection for Classic Way storefront', NULL, true, 9, 'https://placehold.co/900x1100/2d3748/ffffff?text=Premium+Cotton'),
  ('0c04cb7c-69d1-5467-8df7-d86e1402fdf1'::uuid, 'Sports Wear', 'sports-wear', 'Sports Wear collection for Classic Way storefront', NULL, true, 10, 'https://placehold.co/900x1100/2d3748/ffffff?text=Sports+Wear'),
  ('07ac9c07-83eb-5e90-ac06-21152dc913c4'::uuid, 'Kids T-Shirts', 'kids-t-shirts', 'Kids T-Shirts collection for Classic Way storefront', NULL, true, 11, 'https://placehold.co/900x1100/2d3748/ffffff?text=Kids+T-Shirts'),
  ('8ee0e49f-2e66-5c72-9a86-0a8b181648ae'::uuid, 'Unisex Basics', 'unisex-basics', 'Unisex Basics collection for Classic Way storefront', NULL, true, 12, 'https://placehold.co/900x1100/2d3748/ffffff?text=Unisex+Basics')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO inventory_settings (id, low_stock_threshold)
SELECT 'e0823438-feca-5db3-b1e6-06bfeb2baae3'::uuid, 10
WHERE NOT EXISTS (SELECT 1 FROM inventory_settings LIMIT 1);

INSERT INTO store_settings (
  id, store_name, legal_name, email, phone,
  address_line1, city, state, postal_code, country, currency, timezone
)
SELECT
  '154889da-efbd-5180-8088-8e63ec35cd9c'::uuid,
  'Classic Way',
  'Classic Way Retail Pvt Ltd',
  'hello@classicway.example',
  '+91 98765 43210',
  '12 Market Street',
  'Chennai',
  'Tamil Nadu',
  '600001',
  'India',
  'INR',
  'Asia/Kolkata'
WHERE NOT EXISTS (SELECT 1 FROM store_settings LIMIT 1);

INSERT INTO tax_rules (id, name, code, rate_percent, is_inclusive, country, state, is_active, sort_order)
VALUES (
  'b0789e02-5c6e-539a-865b-475b452b162c'::uuid, 'GST 5%', 'GST5', 5.00, false, 'India', NULL, true, 1
)
ON CONFLICT (code) DO NOTHING;

COMMIT;
