-- =============================================================================
-- 03 Coupons (50)
-- Classic Way T-Shirt seed · shared admin + shopping PostgreSQL
-- Generated by database/seeds/generate_tshirt_sql.py
-- UUIDs are deterministic (uuid5) for easy S3 URL updates later.
-- =============================================================================

BEGIN;

INSERT INTO coupons (
  id, code, name, discount_type, discount_value, min_order_amount,
  max_uses, used_count, starts_at, ends_at, is_active, created_at, updated_at
) VALUES
('9b785aff-fcc1-564f-aac8-fc71551f2d2d'::uuid, 'WELCOME10', 'Welcome 10% Off', 'percent', 10.00, NULL, 500, 0, '2026-06-01 10:00:00'::timestamp, '2026-12-28 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('46a5f9ca-93d7-54c1-959c-3771b00e2c73'::uuid, 'FIRSTORDER', 'First Order 15%', 'percent', 15.00, 999.00, 500, 0, '2026-06-01 10:00:00'::timestamp, '2026-12-28 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('1ea612c8-2ee3-5910-8cd2-52287da2af7c'::uuid, 'FLAT150', 'Flat ₹150 Off', 'fixed', 150.00, 799.00, 500, 0, '2026-06-01 10:00:00'::timestamp, '2026-12-28 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('f104aa99-049c-5fa8-a024-39579d722457'::uuid, 'FREESHIP', 'Free Shipping Credit', 'fixed', 59.00, 499.00, 500, 0, '2026-06-01 10:00:00'::timestamp, '2026-12-28 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('df9cc72e-d64e-5428-9e83-df10f96f64f8'::uuid, 'FESTIVE20', 'Festival 20% Off', 'percent', 20.00, 1299.00, 500, 0, '2026-06-01 10:00:00'::timestamp, '2026-12-28 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('64d4315c-d740-5384-8d3d-3fa8f6de9e1b'::uuid, 'TEE01', 'Tee Offer 1', 'fixed', 60.00, 600.00, 101, 1, '2026-06-30 10:00:00'::timestamp, '2026-08-31 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('b164660e-db51-5d42-a971-3f2210f4ba5d'::uuid, 'TEE02', 'Tee Offer 2', 'percent', 7.00, 700.00, 102, 2, '2026-06-29 10:00:00'::timestamp, '2026-09-01 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('c739a1c8-3e45-53f2-a751-fe3510a21d68'::uuid, 'TEE03', 'Tee Offer 3', 'fixed', 80.00, 800.00, 103, 3, '2026-06-28 10:00:00'::timestamp, '2026-09-02 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('7a76a090-71be-5279-bdc9-220422e1d4e1'::uuid, 'TEE04', 'Tee Offer 4', 'percent', 9.00, 900.00, 104, 4, '2026-06-27 10:00:00'::timestamp, '2026-09-03 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('3b0f219e-714f-5566-a3f5-7e8501c8d8ae'::uuid, 'TEE05', 'Tee Offer 5', 'fixed', 100.00, 500.00, 105, 5, '2026-06-26 10:00:00'::timestamp, '2026-09-04 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('870a164a-8854-53cc-8f8a-5db41736166b'::uuid, 'TEE06', 'Tee Offer 6', 'percent', 11.00, 600.00, 106, 6, '2026-06-25 10:00:00'::timestamp, '2026-09-05 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('738c9906-d31f-57ef-953c-8f5b221221ea'::uuid, 'TEE07', 'Tee Offer 7', 'fixed', 120.00, 700.00, 107, 7, '2026-06-24 10:00:00'::timestamp, '2026-09-06 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('e337c09d-4372-5ab7-9b4c-4ca243348e5f'::uuid, 'TEE08', 'Tee Offer 8', 'percent', 13.00, 800.00, 108, 8, '2026-06-23 10:00:00'::timestamp, '2026-09-07 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('66026a43-4d2a-5317-9537-c0d0b7f52ee5'::uuid, 'TEE09', 'Tee Offer 9', 'fixed', 140.00, 900.00, 109, 9, '2026-06-22 10:00:00'::timestamp, '2026-09-08 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('a38a76b0-528b-5848-aadd-99286b033a2e'::uuid, 'TEE10', 'Tee Offer 10', 'percent', 15.00, 500.00, 110, 10, '2026-06-21 10:00:00'::timestamp, '2026-09-09 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('a7531425-567d-5a70-9abd-5971ab2a9b9d'::uuid, 'TEE11', 'Tee Offer 11', 'fixed', 60.00, 600.00, 111, 11, '2026-06-20 10:00:00'::timestamp, '2026-09-10 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('9e29e813-5cc3-51a0-8125-b09a65e06278'::uuid, 'TEE12', 'Tee Offer 12', 'percent', 17.00, 700.00, 112, 0, '2026-06-19 10:00:00'::timestamp, '2026-09-11 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('47041392-5fc4-532f-8611-33a8ce34dcd6'::uuid, 'TEE13', 'Tee Offer 13', 'fixed', 80.00, 800.00, 113, 1, '2026-06-18 10:00:00'::timestamp, '2026-09-12 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('c54dd05c-adf8-557a-b363-ae3e0d997b73'::uuid, 'TEE14', 'Tee Offer 14', 'percent', 19.00, 900.00, 114, 2, '2026-06-17 10:00:00'::timestamp, '2026-09-13 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('71456fa9-3e23-519e-a528-2c555829cf7b'::uuid, 'TEE15', 'Tee Offer 15', 'fixed', 100.00, 500.00, 115, 3, '2026-06-16 10:00:00'::timestamp, '2026-09-14 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('a9b5d7ca-4614-5d61-995d-6c7df6f00cf5'::uuid, 'TEE16', 'Tee Offer 16', 'percent', 21.00, 600.00, 116, 4, '2026-06-15 10:00:00'::timestamp, '2026-09-15 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('34ce7409-6b0c-5ded-9fec-a5dc2ff98dfe'::uuid, 'TEE17', 'Tee Offer 17', 'fixed', 120.00, 700.00, 117, 5, '2026-06-14 10:00:00'::timestamp, '2026-09-16 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('37356670-d6e9-529f-970c-d02f6b7343f6'::uuid, 'TEE18', 'Tee Offer 18', 'percent', 23.00, 800.00, 118, 6, '2026-06-13 10:00:00'::timestamp, '2026-09-17 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('7d1b3cb8-93a5-5d2f-9578-ddba83dc153e'::uuid, 'TEE19', 'Tee Offer 19', 'fixed', 140.00, 900.00, 119, 7, '2026-06-12 10:00:00'::timestamp, '2026-09-18 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('b91b84ef-2357-5c75-84a7-d70bb393ffb3'::uuid, 'TEE20', 'Tee Offer 20', 'percent', 5.00, 500.00, 120, 8, '2026-06-11 10:00:00'::timestamp, '2026-09-19 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('5fdd21fb-e0a4-5c3c-a699-64b47d1c0be3'::uuid, 'TEE21', 'Tee Offer 21', 'fixed', 60.00, 600.00, 121, 9, '2026-06-10 10:00:00'::timestamp, '2026-09-20 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('fced434c-7af5-5e47-a6fd-fb8934e59479'::uuid, 'TEE22', 'Tee Offer 22', 'percent', 7.00, 700.00, 122, 10, '2026-06-09 10:00:00'::timestamp, '2026-09-21 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('f81ec798-ca01-5c76-a03e-72904a1b327a'::uuid, 'TEE23', 'Tee Offer 23', 'fixed', 80.00, 800.00, 123, 11, '2026-06-08 10:00:00'::timestamp, '2026-09-22 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('6475cb5c-4080-5f5b-90ab-f330216dab9d'::uuid, 'TEE24', 'Tee Offer 24', 'percent', 9.00, 900.00, 124, 0, '2026-06-07 10:00:00'::timestamp, '2026-09-23 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('c0c1e48e-3780-5d34-bbcb-15cf3bc982ac'::uuid, 'TEE25', 'Tee Offer 25', 'fixed', 100.00, 500.00, 125, 1, '2026-06-06 10:00:00'::timestamp, '2026-09-24 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('93fcf45f-356a-582a-ba90-603f6ab90fde'::uuid, 'TEE26', 'Tee Offer 26', 'percent', 11.00, 600.00, 126, 2, '2026-06-05 10:00:00'::timestamp, '2026-09-25 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('0c917002-b9ef-57c7-a1b5-f867f4210789'::uuid, 'TEE27', 'Tee Offer 27', 'fixed', 120.00, 700.00, 127, 3, '2026-06-04 10:00:00'::timestamp, '2026-09-26 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('a484db1c-6a4d-51c9-b068-966d720b3b29'::uuid, 'TEE28', 'Tee Offer 28', 'percent', 13.00, 800.00, 128, 4, '2026-06-03 10:00:00'::timestamp, '2026-09-27 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('991f8606-893c-56a7-a8e6-79ae84e25213'::uuid, 'TEE29', 'Tee Offer 29', 'fixed', 140.00, 900.00, 129, 5, '2026-06-02 10:00:00'::timestamp, '2026-09-28 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('09bdc2a6-4421-54f4-81e2-9b4c2929a78c'::uuid, 'TEE30', 'Tee Offer 30', 'percent', 15.00, 500.00, 130, 6, '2026-06-01 10:00:00'::timestamp, '2026-09-29 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('8b814d15-7b08-50e5-8395-9d077c994112'::uuid, 'TEE31', 'Tee Offer 31', 'fixed', 60.00, 600.00, 131, 7, '2026-05-31 10:00:00'::timestamp, '2026-09-30 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('cd44c020-f3fb-50b6-b164-4b8520356ee9'::uuid, 'TEE32', 'Tee Offer 32', 'percent', 17.00, 700.00, 132, 8, '2026-05-30 10:00:00'::timestamp, '2026-10-01 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('cbaea005-1d81-5cc6-a703-5d7ac06a8f77'::uuid, 'TEE33', 'Tee Offer 33', 'fixed', 80.00, 800.00, 133, 9, '2026-05-29 10:00:00'::timestamp, '2026-10-02 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('b17e40b8-46c6-5650-8434-f5d7580b0481'::uuid, 'TEE34', 'Tee Offer 34', 'percent', 19.00, 900.00, 134, 10, '2026-05-28 10:00:00'::timestamp, '2026-10-03 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('08f04faa-c49f-5e6e-a1cf-5ec98042f37d'::uuid, 'TEE35', 'Tee Offer 35', 'fixed', 100.00, 500.00, 135, 11, '2026-05-27 10:00:00'::timestamp, '2026-10-04 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('8819c5c8-565a-57db-8f33-455462152d26'::uuid, 'TEE36', 'Tee Offer 36', 'percent', 21.00, 600.00, 136, 0, '2026-05-26 10:00:00'::timestamp, '2026-10-05 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('211698e5-cc08-533e-9693-4cba18aaace2'::uuid, 'TEE37', 'Tee Offer 37', 'fixed', 120.00, 700.00, 137, 1, '2026-05-25 10:00:00'::timestamp, '2026-10-06 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('5387c8db-121b-5e20-8f3c-fa009bdf2d99'::uuid, 'TEE38', 'Tee Offer 38', 'percent', 23.00, 800.00, 138, 2, '2026-05-24 10:00:00'::timestamp, '2026-10-07 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('46408fe1-8d73-5fbd-8f03-f4c2b9894c47'::uuid, 'TEE39', 'Tee Offer 39', 'fixed', 140.00, 900.00, 139, 3, '2026-05-23 10:00:00'::timestamp, '2026-10-08 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('b8c33f42-0dc3-5894-afbf-b9aa59a4cbc0'::uuid, 'TEE40', 'Tee Offer 40', 'percent', 5.00, 500.00, 140, 4, '2026-05-22 10:00:00'::timestamp, '2026-10-09 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('805b6bd6-4588-51ed-a522-dcb0d0117570'::uuid, 'TEE41', 'Tee Offer 41', 'fixed', 60.00, 600.00, 141, 5, '2026-05-21 10:00:00'::timestamp, '2026-10-10 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('50a2dd51-c1f3-5a8d-ace0-0d6dabd1a97e'::uuid, 'TEE42', 'Tee Offer 42', 'percent', 7.00, 700.00, 142, 6, '2026-05-20 10:00:00'::timestamp, '2026-10-11 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('9b67a8b5-e8b0-5f23-ab93-dafbe91bf0ad'::uuid, 'TEE43', 'Tee Offer 43', 'fixed', 80.00, 800.00, 143, 7, '2026-05-19 10:00:00'::timestamp, '2026-10-12 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('b03babe8-0c81-5589-b287-803f5c3b3ce8'::uuid, 'TEE44', 'Tee Offer 44', 'percent', 9.00, 900.00, 144, 8, '2026-05-18 10:00:00'::timestamp, '2026-10-13 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp),
('32f68b18-7a8e-5bbe-9ed8-09475e1006a5'::uuid, 'TEE45', 'Tee Offer 45', 'fixed', 100.00, 500.00, 145, 9, '2026-05-17 10:00:00'::timestamp, '2026-10-14 10:00:00'::timestamp, true, '2026-07-01 10:00:00'::timestamp, '2026-07-01 10:00:00'::timestamp)
ON CONFLICT (code) DO NOTHING;

COMMIT;
