-- =============================================================================
-- Verify seed row counts (dashboard readiness)
-- Classic Way T-Shirt seed · shared admin + shopping PostgreSQL
-- Generated by database/seeds/generate_tshirt_sql.py
-- UUIDs are deterministic (uuid5) for easy S3 URL updates later.
-- =============================================================================

BEGIN;


SELECT 'brands' AS entity, count(*)::int AS rows FROM brands
UNION ALL SELECT 'categories', count(*)::int FROM categories
UNION ALL SELECT 'attribute_definitions', count(*)::int FROM attribute_definitions
UNION ALL SELECT 'products', count(*)::int FROM products
UNION ALL SELECT 'product_variants', count(*)::int FROM product_variants
UNION ALL SELECT 'product_media', count(*)::int FROM product_media
UNION ALL SELECT 'inventory_items', count(*)::int FROM inventory_items
UNION ALL SELECT 'coupons', count(*)::int FROM coupons
UNION ALL SELECT 'customers', count(*)::int FROM customers
UNION ALL SELECT 'customer_addresses', count(*)::int FROM customer_addresses
UNION ALL SELECT 'wishlists', count(*)::int FROM wishlists
UNION ALL SELECT 'wishlist_items', count(*)::int FROM wishlist_items
UNION ALL SELECT 'carts', count(*)::int FROM carts
UNION ALL SELECT 'cart_items', count(*)::int FROM cart_items
UNION ALL SELECT 'orders', count(*)::int FROM orders
UNION ALL SELECT 'order_items', count(*)::int FROM order_items
UNION ALL SELECT 'payments', count(*)::int FROM payments
UNION ALL SELECT 'refunds', count(*)::int FROM refunds
UNION ALL SELECT 'shipments', count(*)::int FROM shipments
UNION ALL SELECT 'reviews', count(*)::int FROM reviews
UNION ALL SELECT 'notifications', count(*)::int FROM notifications
ORDER BY 1;

-- Order status mix for admin dashboard
SELECT status, count(*)::int AS orders FROM orders GROUP BY status ORDER BY 1;

-- Low stock SKUs (threshold 10)
SELECT sku, quantity FROM inventory_items WHERE quantity <= 10 ORDER BY quantity ASC LIMIT 20;

COMMIT;
