"""Story rows for PROJECT_TRACKING.xlsx — VL foundation + VS shopping sync."""

from datetime import date, timedelta

START = date(2026, 7, 14)


def week_date(week_offset: int, weekday: int = 0) -> date:
    base_monday = START - timedelta(days=START.weekday())
    return base_monday + timedelta(weeks=week_offset - 1, days=weekday)


# Columns:
# ID, Date, Phase, Week, Module, Title, User Story, Branch, Type,
# Priority, Status, Owner, Estimate, Depends On, Acceptance, Notes

VL_STORIES = [
    ("VL-001", week_date(1), "P0 Foundation", 1, "Platform", "Project bootstrap & Docker network",
     "As a developer, I can run the full stack with docker compose so local setup is consistent.",
     "feat/platform-docker-compose", "feat", "P0", "Done", "Backend", 2, "-",
     "Compose brings up postgres, admin/shopping backends and frontends", "PostgreSQL network"),
    ("VL-002", week_date(1), "P0 Foundation", 1, "Backend", "Layered FastAPI structure",
     "As a developer, I have model/schema/repository/service/route layers for maintainable APIs.",
     "feat/backend-layered-structure", "feat", "P0", "Done", "Backend", 2, "VL-001",
     "Folders and imports follow agreed architecture", "Modular monolith"),
    ("VL-003", week_date(1), "P0 Foundation", 1, "Auth", "JWT login + Argon2 passwords",
     "As an admin, I can securely sign in and receive an access token.",
     "feat/auth-jwt-login", "feat", "P0", "Done", "Backend", 2, "VL-002",
     "Login returns token; invalid credentials rejected", "OAuth2 password form"),
    ("VL-004", week_date(1), "P0 Foundation", 1, "RBAC", "Default roles seed (admin/manager/viewer)",
     "As the system, I seed default roles and an initial admin user on first boot.",
     "feat/rbac-default-roles-seed", "feat", "P0", "Done", "Backend", 1, "VL-003",
     "admin/manager/viewer exist; initial admin can login", "Credentials via env"),
    ("VL-005", week_date(2), "P0 Foundation", 2, "Users", "User CRUD APIs",
     "As an admin, I can create, list, update, and delete users with role assignment.",
     "feat/users-crud-api", "feat", "P0", "Done", "Backend", 2, "VL-004",
     "All CRUD endpoints work with RBAC guards", "Admin-only write"),
    ("VL-006", week_date(2), "P0 Foundation", 2, "Roles", "Role CRUD APIs",
     "As an admin, I can manage custom roles while system roles stay protected.",
     "feat/roles-crud-api", "feat", "P0", "Done", "Backend", 1, "VL-004",
     "Cannot delete/rename protected roles unsafely", "Name update supported"),
    ("VL-007", week_date(2), "P0 Foundation", 2, "Frontend", "Light glass admin shell + Redux store",
     "As an admin, I use a light glassmorphism UI with Redux-managed auth/users/roles.",
     "feat/admin-glass-ui-redux", "feat", "P0", "Done", "Frontend", 3, "VL-005",
     "Login + dashboard match UI standards", "No dark theme"),
    ("VL-008", week_date(2), "P0 Foundation", 2, "Frontend", "User/Role edit modals + confirm delete",
     "As an admin, I can edit users/roles in modals and must confirm deletes.",
     "feat/admin-edit-confirm-modals", "feat", "P0", "Done", "Frontend", 2, "VL-007",
     "Edit works; delete uses ConfirmDialog", "Mobile responsive cards"),
    ("VL-009", week_date(2), "P0 Foundation", 2, "Database", "PostgreSQL schema + Alembic migrations",
     "As a developer, schema changes are versioned with Alembic on PostgreSQL.",
     "feat/alembic-postgresql-schema", "feat", "P0", "Done", "Backend", 2, "VL-002",
     "alembic upgrade head creates core tables", "Migrated from MySQL"),
    ("VL-010", week_date(3), "P1 Catalog", 3, "Catalog", "Category CRUD",
     "As an admin, I can create and organize product categories.",
     "feat/catalog-categories", "feat", "P1", "Done", "Backend", 3, "VL-009",
     "Nested or flat categories with active flag", "Admin UI live"),
    ("VL-011", week_date(3), "P1 Catalog", 3, "Catalog", "Product create/edit with media",
     "As an admin, I can publish products with images, price, and description.",
     "feat/catalog-products-media", "feat", "P1", "Done", "Fullstack", 5, "VL-010",
     "Product visible in admin list; media upload works", "Local uploads volume"),
    ("VL-012", week_date(4), "P1 Catalog", 4, "Catalog", "Product variants (size/color)",
     "As an admin, I can define variants with SKU and price overrides.",
     "feat/catalog-product-variants", "feat", "P1", "Done", "Backend", 4, "VL-011",
     "Variants persist and appear in product detail", "JSON options"),
    ("VL-013", week_date(4), "P1 Catalog", 4, "Inventory", "Stock levels & low-stock alerts",
     "As a manager, I can monitor stock and get low-stock warnings.",
     "feat/inventory-stock-alerts", "feat", "P1", "Done", "Fullstack", 4, "VL-012",
     "Stock updates on admin; alert threshold configurable", "Inventory panel"),
    ("VL-014", week_date(5), "P1 Catalog", 5, "Storefront", "Public catalog browse & product detail",
     "As a customer, I can browse products and open product details.",
     "feat/storefront-catalog-browse", "feat", "P1", "Done", "Frontend", 5, "VL-011",
     "Listing + detail pages responsive", "Shopping + admin /store"),
    ("VL-015", week_date(6), "P2 Orders", 6, "Cart", "Cart add/update/remove",
     "As a customer, I can manage cart items before checkout.",
     "feat/cart-management", "feat", "P1", "Done", "Fullstack", 4, "VL-014",
     "Guest + logged-in cart supported", "Shopping cart API"),
    ("VL-016", week_date(6), "P2 Orders", 6, "Checkout", "Address book & shipping quote",
     "As a customer, I can select delivery address and see shipping estimate.",
     "feat/checkout-address-shipping", "feat", "P1", "Done", "Fullstack", 5, "VL-015",
     "Address validation + quote returned", "Customer addresses"),
    ("VL-017", week_date(7), "P2 Orders", 7, "Orders", "Create order lifecycle APIs",
     "As the system, I create orders with line items and status machine.",
     "feat/orders-lifecycle-api", "feat", "P0", "Done", "Backend", 5, "VL-016",
     "Statuses pending/paid/cancelled/return supported", "Shared orders table"),
    ("VL-018", week_date(8), "P2 Orders", 8, "Admin", "Admin order list & detail",
     "As an admin, I can view and filter orders with line-item detail.",
     "feat/admin-orders-console", "feat", "P1", "Done", "Frontend", 4, "VL-017",
     "Filters by status/date; detail shows totals", "OrdersPanel"),
    ("VL-019", week_date(9), "P3 Payments", 9, "Payments", "Razorpay order + checkout SDK",
     "As a customer, I can pay for an order via Razorpay checkout.",
     "feat/payments-razorpay-checkout", "feat", "P0", "In Progress", "Fullstack", 5, "VL-017",
     "Sandbox payment succeeds and maps to order", "Demo provider + real wiring"),
    ("VL-020", week_date(9), "P3 Payments", 9, "Payments", "Payment webhook + signature verify",
     "As the system, I verify gateway webhooks and update payment status idempotently.",
     "feat/payments-razorpay-webhook", "feat", "P0", "In Progress", "Backend", 4, "VL-019",
     "Invalid signature rejected; duplicate events ignored", "Demo signature gate"),
    ("VL-021", week_date(10), "P3 Payments", 10, "Payments", "Refunds & COD flow",
     "As an admin, I can refund paid orders; customers can choose COD where allowed.",
     "feat/payments-refunds-cod", "feat", "P1", "Done", "Fullstack", 4, "VL-020",
     "Partial/full refund + COD order path verified", "COD path live"),
    ("VL-022", week_date(11), "P4 Courier", 11, "Courier", "Courier adapter interface",
     "As a developer, I can plug multiple courier partners behind one service contract.",
     "feat/courier-adapter-interface", "feat", "P0", "Done", "Backend", 3, "VL-021",
     "create/cancel/track/label methods defined", "Manual adapter included"),
    ("VL-023", week_date(11), "P4 Courier", 11, "Courier", "Shiprocket/Delhivery shipment create",
     "As an ops user, I can create a shipment and receive an AWB for a paid order.",
     "feat/courier-create-shipment-awb", "feat", "P0", "In Progress", "Backend", 5, "VL-022",
     "AWB saved on shipment; label URL available", "Needs partner credentials"),
    ("VL-024", week_date(12), "P4 Courier", 12, "Courier", "Label print & pickup scheduling",
     "As warehouse staff, I can print labels and schedule pickups.",
     "feat/courier-labels-pickup", "feat", "P1", "In Progress", "Fullstack", 4, "VL-023",
     "Label downloadable; pickup confirmation stored", "Shipments panel"),
    ("VL-025", week_date(13), "P5 Tracking", 13, "Tracking", "Shipment event ingestion",
     "As the system, I ingest courier webhooks/polls into shipment_events.",
     "feat/tracking-shipment-events", "feat", "P0", "Done", "Backend", 4, "VL-023",
     "Timeline events ordered by timestamp", "Admin events API"),
    ("VL-026", week_date(13), "P5 Tracking", 13, "Tracking", "Customer order tracking page",
     "As a customer, I can track my order with a clear status timeline.",
     "feat/tracking-customer-timeline-ui", "feat", "P0", "In Progress", "Frontend", 4, "VL-025",
     "Shows Placed→Delivered stages with AWB", "Wire shipment events next"),
    ("VL-027", week_date(14), "P5 Tracking", 14, "Notify", "Order/shipment notifications",
     "As a customer, I receive email/SMS updates for payment and shipment milestones.",
     "feat/notifications-order-shipment", "feat", "P1", "In Progress", "Backend", 4, "VL-026",
     "Templates for paid/shipped/delivered", "Admin send exists; delivery TBD"),
    ("VL-028", week_date(14), "P5 Tracking", 14, "Admin", "Exception queue & manual override",
     "As ops, I can manage delayed/RTO shipments and log manual overrides.",
     "feat/tracking-exception-queue", "feat", "P1", "Done", "Fullstack", 3, "VL-025",
     "Override requires reason; audited", "Exceptions panel"),
    ("VL-029", week_date(15), "P6 Launch", 15, "Reports", "Sales & fulfillment dashboard",
     "As a business owner, I can view sales, payment, and delivery KPIs.",
     "feat/reports-sales-fulfillment", "feat", "P1", "Done", "Fullstack", 4, "VL-021",
     "Daily/weekly charts and CSV export", "Reports panel"),
    ("VL-030", week_date(15), "P6 Launch", 15, "QA", "UAT script & bugfix sprint",
     "As the client, I can execute UAT and log defects against stories.",
     "fix/uat-bugfix-pass", "fix", "P0", "In Progress", "QA", 5, "VL-027",
     "Critical bugs closed; UAT sign-off recorded", "Shopping UAT added"),
    ("VL-031", week_date(16), "P6 Launch", 16, "Ops", "Staging → production cutover",
     "As the team, we deploy production with migrations, secrets, and monitoring.",
     "feat/prod-cutover-checklist", "feat", "P0", "Planned", "DevOps", 3, "VL-030",
     "HTTPS, backups, smoke tests green", "Postgres cutover"),
    ("VL-032", week_date(16), "P6 Launch", 16, "Docs", "Client runbook & training",
     "As the client ops team, I have a runbook for daily admin tasks.",
     "docs/client-ops-runbook", "docs", "P2", "In Progress", "PM", 2, "VL-031",
     "Runbook covers users, orders, refunds, shipments", "Update for shopping"),
]

VS_STORIES = [
    ("VS-001", week_date(5), "S1 Theme", 5, "Shopping UI", "Fashion theme baseline (BlueBerry)",
     "As a shopper, I see a fashion-ready Valaiyagam storefront using the BlueBerry theme.",
     "feat/vs-001-fashion-theme-baseline", "feat", "P0", "Done", "Frontend", 3, "VL-014",
     "Theme loads on :3001; brand renamed Valaiyagam Fashion", "shopping/frontend"),
    ("VS-002", week_date(5), "S1 Theme", 5, "Shopping UI", "Header/footer categories from API",
     "As a shopper, navigation categories come from admin-managed categories.",
     "feat/vs-002-nav-categories-api", "feat", "P0", "Done", "Frontend", 2, "VS-001",
     "Header/menu uses GET /categories; empty state handled", "Replace static chips"),
    ("VS-003", week_date(5), "S1 Theme", 5, "Shopping UI", "Remove static catalog fallback",
     "As an admin, unpublished/empty catalog is not masked by demo static products.",
     "feat/vs-003-api-only-catalog", "feat", "P0", "Done", "Frontend", 2, "VS-001",
     "Shop/home show empty state when API returns zero published products", "Critical for UAT honesty"),
    ("VS-004", week_date(5), "S2 Catalog Sync", 5, "Catalog Sync", "Admin publish reflects on shopping",
     "As an admin, when I publish a product it appears on the shopping site without redeploy.",
     "feat/vs-004-publish-reflects-shopping", "feat", "P0", "Done", "Fullstack", 3, "VL-011",
     "is_published+public+active product visible on /shop and PDP within refresh", "Shared products table"),
    ("VS-005", week_date(5), "S2 Catalog Sync", 5, "Catalog Sync", "Category sync to shop filters",
     "As a shopper, I can filter products by admin categories and subcategories.",
     "feat/vs-005-category-filter-sync", "feat", "P0", "Done", "Fullstack", 2, "VL-010",
     "GET /categories and category products match admin tree", "-"),
    ("VS-006", week_date(6), "S2 Catalog Sync", 6, "Catalog Sync", "Product media gallery sync",
     "As a shopper, I see admin-uploaded images on the product gallery.",
     "feat/vs-006-media-gallery-sync", "feat", "P0", "Done", "Fullstack", 2, "VL-011",
     "Primary + gallery images load from /uploads via shopping API origin", "-"),
    ("VS-007", week_date(6), "S2 Catalog Sync", 6, "Catalog Sync", "Size/color variants on shopping",
     "As a shopper, I select size/color variants created in admin before add-to-cart.",
     "feat/vs-007-variant-selection", "feat", "P0", "Done", "Fullstack", 3, "VL-012",
     "Variant SKU/stock enforced; filters size/color work on listing", "-"),
    ("VS-008", week_date(6), "S2 Catalog Sync", 6, "Catalog", "Brand CRUD in admin + shop filter",
     "As an admin, I manage brands; shoppers filter by brand on shopping.",
     "feat/vs-008-brand-admin-crud", "feat", "P1", "Done", "Fullstack", 3, "VS-004",
     "Admin Brands panel; product brand_id; GET /brands used in shop", "Gap today"),
    ("VS-009", week_date(6), "S2 Catalog Sync", 6, "Catalog", "Merchandising flags UI",
     "As an admin, I mark products featured/trending/best-seller for shopping home tabs.",
     "feat/vs-009-merchandising-flags-ui", "feat", "P1", "Done", "Fullstack", 2, "VS-004",
     "Admin form toggles flags; shopping featured/trending/best-sellers endpoints return them", "Flags exist in DB"),
    ("VS-010", week_date(7), "S2 Catalog Sync", 7, "Shopping API", "Live search & suggestions",
     "As a shopper, search and typeahead use the live published catalog.",
     "feat/vs-010-search-suggestions", "feat", "P1", "Done", "Fullstack", 2, "VS-004",
     "GET /products/search and /suggestions return admin products only", "-"),
    ("VS-011", week_date(7), "S3 Commerce", 7, "Auth", "Customer register/login/refresh",
     "As a customer, I can register, login, refresh tokens, and logout securely.",
     "feat/vs-011-customer-auth", "feat", "P0", "Done", "Fullstack", 3, "VL-003",
     "JWT access+refresh; /auth/me works; tokens stored securely on client", "customers table"),
    ("VS-012", week_date(7), "S3 Commerce", 7, "Cart", "Guest cart merge after login",
     "As a customer, my guest cart merges into my account cart after login.",
     "feat/vs-012-guest-cart-merge", "feat", "P0", "Done", "Fullstack", 2, "VS-011",
     "POST /cart/merge combines lines; no duplicate variants", "-"),
    ("VS-013", week_date(8), "S3 Commerce", 8, "Engagement", "Wishlist & compare theme pages",
     "As a shopper, I can wishlist and compare products using theme pages backed by APIs.",
     "feat/vs-013-wishlist-compare", "feat", "P1", "Done", "Fullstack", 3, "VS-011",
     "Wishlist/compare persist for logged-in users; max 4 compare items", "-"),
    ("VS-014", week_date(8), "S3 Commerce", 8, "Checkout", "Customer address book",
     "As a customer, I manage multiple addresses and set a default for checkout.",
     "feat/vs-014-address-book", "feat", "P0", "Done", "Fullstack", 2, "VS-011",
     "CRUD + PUT default; addresses scoped to customer_id", "-"),
    ("VS-015", week_date(8), "S3 Commerce", 8, "Checkout", "Checkout preview/validate/create-order",
     "As a customer, I can preview totals and place an order from my cart.",
     "feat/vs-015-checkout-create-order", "feat", "P0", "Done", "Fullstack", 4, "VS-014",
     "POST /checkout/* creates order with line snapshots and shipping fields", "-"),
    ("VS-016", week_date(9), "S3 Commerce", 9, "Coupons", "Coupon apply/remove on shopping cart",
     "As a customer, I can apply/remove admin coupons and see discount on checkout.",
     "feat/vs-016-coupon-cart-persist", "feat", "P1", "Done", "Fullstack", 2, "VS-015",
     "Coupon stored on cart; validate min/max/expiry; usage recorded on order", "-"),
    ("VS-017", week_date(9), "S3 Commerce", 9, "Payments", "COD + Razorpay create/verify from shopping",
     "As a customer, I can pay COD or via gateway; payment records are created.",
     "feat/vs-017-shopping-payments", "feat", "P0", "Done", "Fullstack", 4, "VS-015",
     "Payments appear for admin; COD stays pending until mark-paid", "Demo provider"),
    ("VS-018", week_date(9), "S4 Admin Reflect", 9, "Orders Sync", "Shopping order visible in Admin Orders",
     "As an admin, every shopping-placed order appears in the Orders panel immediately.",
     "feat/vs-018-order-admin-reflect", "feat", "P0", "Done", "Fullstack", 2, "VS-015",
     "Filter/search finds order_number; detail shows customer_id lines and totals", "Shared orders table"),
    ("VS-019", week_date(10), "S4 Admin Reflect", 10, "Orders Sync", "Admin mark-paid/cancel updates shopping",
     "As a customer, admin mark-paid/cancel is reflected when I fetch order/tracking.",
     "feat/vs-019-admin-status-to-shopping", "feat", "P0", "Done", "Fullstack", 2, "VS-018",
     "GET /orders/{id} and tracking show updated status_history", "-"),
    ("VS-020", week_date(10), "S4 Admin Reflect", 10, "Inventory Sync", "Checkout reserves admin inventory",
     "As ops, shopping checkout reserves/deducts stock visible in Inventory panel.",
     "feat/vs-020-inventory-reserve-sync", "feat", "P0", "Done", "Backend", 3, "VL-013",
     "Stock movements created; oversell blocked when stock insufficient", "-"),
    ("VS-021", week_date(10), "S4 Admin Reflect", 10, "Customers", "Admin Customers console",
     "As an admin, I can list/search/disable shopping customers and view their orders.",
     "feat/vs-021-admin-customers-console", "feat", "P1", "Done", "Fullstack", 4, "VS-011",
     "Customers tab with status toggle; link to orders", "Gap today"),
    ("VS-022", week_date(11), "S4 Admin Reflect", 11, "Coupons", "Coupon usage audit in admin",
     "As an admin, I can see which customers used which coupons on which orders.",
     "feat/vs-022-coupon-usage-audit", "feat", "P2", "Done", "Fullstack", 2, "VS-016",
     "Admin view of coupon_usages with customer/order links", "-"),
    ("VS-023", week_date(11), "S4 Admin Reflect", 11, "Reviews", "Review moderation in admin",
     "As an admin, I approve/reject product reviews submitted from shopping.",
     "feat/vs-023-review-moderation", "feat", "P1", "Done", "Fullstack", 3, "VS-007",
     "Only approved reviews show on PDP; admin panel lists pending", "is_approved exists"),
    ("VS-024", week_date(12), "S5 Fulfillment", 12, "Tracking", "Admin shipment → shopping track",
     "As a customer, tracking shows admin shipment AWB and status events.",
     "feat/vs-024-shipment-to-track", "feat", "P0", "Done", "Fullstack", 4, "VL-025",
     "Track page merges order_status_history + shipment_events", "Primary loop"),
    ("VS-025", week_date(12), "S5 Fulfillment", 12, "Orders", "Full order status machine on shopping",
     "As a customer, I can cancel/return/reorder and see statuses matching admin lifecycle.",
     "feat/vs-025-order-status-machine", "feat", "P0", "Done", "Backend", 3, "VS-018",
     "cancel/return/reorder/invoice endpoints work with auth", "-"),
    ("VS-026", week_date(13), "S5 Fulfillment", 13, "Notify", "Customer order notifications",
     "As a customer, I receive notifications when order is paid/shipped/delivered.",
     "feat/vs-026-customer-notifications", "feat", "P1", "Done", "Backend", 4, "VS-024",
     "Email/SMS templates fired from status transitions", "Provider TBD"),
    ("VS-027", week_date(14), "S6 Harden", 14, "Checkout", "Tax rules from admin in shopping checkout",
     "As a shopper, tax is calculated from admin tax rules during preview/create-order.",
     "feat/vs-027-tax-rules-checkout", "feat", "P1", "Done", "Backend", 3, "VS-015",
     "tax_amount > 0 when matching tax rule exists", "Currently hardcoded 0"),
    ("VS-028", week_date(15), "S6 Harden", 15, "QA", "E2E UAT publish→buy→fulfill→track→review",
     "As the client, I can run a full admin↔shopping UAT script and sign off.",
     "test/vs-028-shopping-admin-uat", "fix", "P0", "Done", "QA", 5, "VS-024",
     "All workflow A–E steps pass; defects logged to stories", "See UAT_CHECKLIST_SHOPPING.md"),
]

ALL_STORIES = VL_STORIES + VS_STORIES

E2E_WORKFLOWS = [
    ("WF-A", "Publish Product", "Admin", "Shopping",
     "1) Login admin 2) Create category 3) Create product+media+variants 4) Publish public 5) Set stock",
     "6) Open shopping home/shop 7) Find product 8) Open PDP 9) See images/variants/price",
     "VS-004,VS-005,VS-006,VS-007", "P0", "Done"),
    ("WF-B", "Place Order", "Shopping", "Admin",
     "1) Register/login 2) Add variant to cart 3) Apply coupon 4) Address 5) Checkout COD/Razorpay",
     "6) Admin Orders shows order 7) Payments row exists 8) Inventory reserved",
     "VS-011,VS-015,VS-016,VS-017,VS-018,VS-020", "P0", "Done"),
    ("WF-C", "Fulfill & Track", "Admin", "Shopping",
     "1) Mark paid 2) Create shipment+AWB 3) Add events packed/shipped/delivered",
     "4) Customer Track Order timeline updates 5) Optional notification",
     "VS-019,VS-024,VS-025,VS-026", "P0", "Done"),
    ("WF-D", "Catalog Change", "Admin", "Shopping",
     "1) Edit price/image/stock or unpublish",
     "2) Shopping list/PDP reflects change on refresh; unpublished hidden",
     "VS-003,VS-004,VS-006", "P1", "Done"),
    ("WF-E", "Coupon & Offer", "Admin", "Shopping",
     "1) Create coupon with rules in admin",
     "2) Apply on shopping cart/checkout 3) Order stores discount 4) Admin sees usage",
     "VS-016,VS-022", "P1", "Done"),
    ("WF-F", "Review Loop", "Shopping", "Admin",
     "1) Delivered customer submits review+images",
     "2) Admin moderates 3) Approved review appears on PDP",
     "VS-023", "P1", "Done"),
]

TIMELINE_PHASES = [
    ("P0 Foundation", week_date(1), week_date(2, 6), "Auth, RBAC, Docker, UI shell", "M1 Foundation demo", "Admin login + user/role CRUD", "Done"),
    ("P1 Catalog", week_date(3), week_date(5, 6), "Categories, products, inventory", "M2 Catalog demo", "Publish products to storefront", "Done"),
    ("P2 Orders", week_date(6), week_date(8, 6), "Cart, checkout, order lifecycle", "M3 Checkout demo", "Place order end-to-end", "Done"),
    ("P3 Payments", week_date(9), week_date(10, 6), "Gateway, webhooks, refunds, COD", "M4 Payment demo", "Paid order verified", "In Progress"),
    ("P4 Courier", week_date(11), week_date(12, 6), "Adapters, AWB, labels, pickup", "M5 Courier demo", "Shipment created from paid order", "In Progress"),
    ("P5 Tracking", week_date(13), week_date(14, 6), "Timeline UI + notifications", "M6 Tracking demo", "Customer can track order", "In Progress"),
    ("P6 Launch", week_date(15), week_date(16, 6), "Reports, UAT, production cutover", "M7 Go-live", "Production ready checklist", "In Progress"),
    ("S1 Theme", week_date(5), week_date(6, 6), "BlueBerry fashion theme + API nav", "MS1 Theme live", "Shopping UI on :3001 branded", "Done"),
    ("S2 Catalog Sync", week_date(5), week_date(7, 6), "Admin publish → shopping shelf", "MS2 Catalog sync", "Publish reflects on shop", "Done"),
    ("S3 Commerce", week_date(7), week_date(9, 6), "Auth, cart, checkout, payments", "MS3 Buy path", "Customer can place order", "Done"),
    ("S4 Admin Reflect", week_date(9), week_date(11, 6), "Orders/inventory/customers reflection", "MS4 Ops loop", "Admin sees shopping orders", "Done"),
    ("S5 Fulfillment", week_date(12), week_date(13, 6), "Shipment → customer track", "MS5 Track loop", "Track shows AWB/events", "Done"),
    ("S6 Harden", week_date(14), week_date(16, 6), "Tax, reviews, UAT, cutover", "MS6 Sign-off", "Full WF-A–F UAT passed", "Done"),
]
